version: '3'
services:
  app:
    build: .
    volumes:
      - ./client/:/usr/work/
    ports:
      - "3000:3000"
    command: sh -c "yarn build && yarn start"
    restart: always
    tty: true
volumes:
  app_data: